# Generated by Django 5.2 on 2025-05-07 10:42

import blueprint_converter.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint_converter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('light_type', models.CharField(choices=[('ambient', 'Ambient Light'), ('directional', 'Directional Light'), ('point', 'Point Light'), ('spot', 'Spot Light')], max_length=20)),
                ('intensity', models.FloatField(default=1.0)),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('model_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wall', 'Wall Paint'), ('floor', 'Flooring'), ('ceiling', 'Ceiling'), ('door', 'Door'), ('window', 'Window'), ('furniture', 'Furniture')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_data', models.JSONField(default=dict)),
                ('thumbnail', models.ImageField(upload_to=blueprint_converter.models.furniture_image_path)),
                ('width', models.FloatField(help_text='Width in meters')),
                ('depth', models.FloatField(help_text='Depth in meters')),
                ('height', models.FloatField(help_text='Height in meters')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_items', to='blueprint_converter.furniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to=blueprint_converter.models.material_image_path)),
                ('texture_map', models.ImageField(blank=True, null=True, upload_to=blueprint_converter.models.material_image_path)),
                ('normal_map', models.ImageField(blank=True, null=True, upload_to=blueprint_converter.models.material_image_path)),
                ('color_hex', models.CharField(help_text='Hex color code (e.g., #FFFFFF)', max_length=7)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='blueprint_converter.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('furniture_items', models.JSONField(default=list)),
                ('wall_materials', models.JSONField(default=dict)),
                ('floor_materials', models.JSONField(default=dict)),
                ('ceiling_materials', models.JSONField(default=dict)),
                ('door_materials', models.JSONField(default=dict)),
                ('window_materials', models.JSONField(default=dict)),
                ('lighting_setup', models.JSONField(default=list)),
                ('model_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='blueprint_converter.model3d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_customizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_customizations', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
