# Generated by Django 5.2 on 2025-05-07 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint_converter', '0002_furniturecategory_lightingoption_materialtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If enabled, the blueprint will be visible to all users'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL),
        ),
    ]
